.TH DOUB 1
.SH NAME
doub \- prints doubles in filesystems

.SH SYNOPSIS
doub [-r] [DIR]

.SH DESCRIPTION
doub is a program overusing checksums to print files with the same
content in a directory or a directory tree, all duplicates in the same
line, separated by colons.

.SH OPTIONS
.TP
.BI \-r
do the searching recursively in dir.

.SH EXAMPLES
.TP
.B doub | cut -d : -f 2- | tr ':' '\en' | xargs rm
.TP
Remove files with the same contents in the current directory, keeping one.

.SH BUGS
doub can't deal with directories named '-r'.
.P
The output is colon-separated, which doesn't work quite well with
filenames containing colons. But the PATH variable does this as well,
so it seems the best option.
.P
There is a very small chance of false positives because there is no
checking of the file contents, they are only compared with their
hashsum.

.SH "SEE ALSO"
.IR uniq(1),
.IR du(1)

.SH AUTHOR
Tell me how slow it is at pranomestro@gmail.com
