.TH DOUB 1
.SH NAME
doub \- prints doubles in filesystems

.SH SYNOPSIS
doub [-r] [DIR]

.SH DESCRIPTION
doub is a program overusing checksums to print files with the same
content in a directory or a directory tree, all duplicates in the same
line, separated by colons.

.SH OPTIONS
.TP
.BI \-r
do the searching recursively in dir.

.SH EXAMPLES
.PP
.fi
.RS
$ doub | cut -d : -f 2- | tr ':' '\en' | xargs rm
.RE
.fi
removes files with the same contents in the current directory, keeping one.

.SH BUGS
The output is colon-separated, which doesn't work quite well with
filenames containing colons. But the $PATH does this as well,
so it seems the best option.

.SH STATUS
1 if it receives a signal, and 0 when everything is alright.

.SH "SEE ALSO"
.IR uniq(1),
.IR du(1)

.SH AUTHOR
Tell me how slow it is at pranomestro@gmail.com
