.Dd May 11, 2017
.Dt DOUB 1
.Os

.Sh NAME
.Nm doub
.Nd print duplicates in directory trees

.Sh SYNOPSIS
.Nm
.Op Fl r
.Op Ar dir

.Sh DESCRIPTION
.Nm
is prints the duplicate files in
.Ar dir ,
all files with the same content in one line, separated by colons.  When
.Ar dir
is not given, it searches the current directory.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl r
Search for duplicates recursively. If the flag is not
given, the duplicate searching is only done with files in
the current directory. 
.El

.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/doub.XXXXXX
The format of the four temporary files used by
.Nm .
.El

.Sh EXAMPLES
Remove all files with the same content in the current directory,
keeping one:
.Pp
.Dl $ doub | cut -d : -f 2- | tr\ : '\en' | xargs rm

.Sh EXIT STATUS
.Ex -std

.Sh BUGS
The output is colon-separated, which causes problems with filenames
containing colons.

.Sh SEE ALSO
.Xr cut 1 ,
.Xr du 1 ,
.Xr rm 1 ,
.Xr tr 1 ,
.Xr uniq 1 ,
.Xr xargs 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.net
